### ISSUE TITLE
getItem never returns.

### ISSUE THREAD

**Issue by bhgames** [gadfil/rn-async-storage#3]
If I do:

    Alert.alert("begin");
    let value = await AsyncStorage.getItem(key);
    Alert.alert("done");

Done is never fired. Running 0.51.0 on Pixel 2 XL API P.

**Comment by vitorbaraujo** [comment]
Also happening to me, it throws an error telling that `AsyncStorage` is `undefined`

**Comment by tui2tone** [comment]
@vitorbaraujo change import to
`import AsyncStorage from 'rn-async-storage'`
Work for me.
